# Dependencies
markdown:         redcarpet
highlighter:      pygments

# # Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Ricardo Costa
tagline:          'Ricardo Costa'
description:      'Personal page'
url:              http://ricardodpcosta.github.io
baseurl:          /

include:          _research/*
include:          _projects/*

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# # Custom vars
# version:          2.1.0

github:
  repo:           http://github.com/ricardodpcosta
